#!/bin/bash
## Helper script for running tests with stubbed out MPI calls.  This
## works like mpirun only it just ignores the -np argument.
set -e
set -u
cmd=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -np)
            # Ignore -np and its value
            shift
            shift
            ;;
        *)
            cmd+=("$1")
            shift
            ;;
    esac
done

# Execute the command without the "-np" argument
"${cmd[@]}"
